//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalEntities : DbContext
    {
        public HospitalEntities()
            : base("name=HospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Appoinment> Appoinments { get; set; }
        public DbSet<BedTable> BedTables { get; set; }
        public DbSet<Doctor> Doctors { get; set; }
        public DbSet<FeeTable> FeeTables { get; set; }
        public DbSet<PatientInfo> PatientInfoes { get; set; }
        public DbSet<Receptionist> Receptionists { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Transection> Transections { get; set; }
    }
}
